
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pirátská strana | Šablona stránek
email: to@pirati.cz
description: > # this means to ignore newlines until "baseurl:"
  Zde doplně popis webu
url: "https://pirati.cz" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-environment-variables

paginate_path: "/aktuality/:num/"
paginate: 11

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-piraatit.gemspec
  - node_modules
  - package.json
  - package-lock.json
  - vendor
  - assets/js
  - config

sass:
  style: compressed
  load_paths:
    - _sass
    - node_modules

js_base_url: '/assets/js/'

# Make sure webpack-generated assets are not purged by Jekyll
keep_files:
  - assets/js

permalink: /aktuality/:title.html

collections:
  people:
    output: true
    permalink: /lide/:path/

  program:
    output: true
    permalink: /komunalni-volby/program/:path/

  # Sole purpose is to create candidate lists in separate files.
  candidatelists:
    output: false

defaults:   # defaults values for collection scope
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
  -
    scope:
      path: "_people"
    values:
      layout: "person"
      rbar:
         - foto
         - personContact
         - people
  -
    scope:
      path: "_program"
    values:
      layout: "program-post"
      rbar:
         - garant
         - program

emptyArray: []

organization:
  name: Jmeno skupiny používající web - př Pirástá strana
  shortName: Název skupiny
  email: example@pirati.cz
  phone: +420 777 123 456 789
  address: |
    Piratská planeta 1
    100 00 Pirátsko
  residenceImg: people/ppp.jpg
  mapLink: https://mapy.cz/zakladni?base=ophoto&q=Radou%C5%A1ova%2014,%20Chrudim
  redmineLink: https://redmine.pirati.cz/projects
  dataBoxId: b2i4r6j
  transparentAccount: 2100048174/2010

# Items listed in contact summary table
contactSummaryItems:
  - type: organizationEmail
  - type: organizationRedmineLink
  - type: organizationPhone
  - type: organizationTransparentAccount
    includeMoreLink: true
  - type: organizationDataBox
  - type: piratiRootWebsite
  - type: custom
    iconClass: fa fa-envelope
    label: Vlastní řádek tabulky
    body: <a href="http://example.com">link</a>

calendar:
  # To enable a nicer calendar, make sure you start jekyll with GOOGLE_CALENDAR_APIKEY=[apikey] bundle exec jekyll serve
  title: Celostátní kalendář
  id: nk73m1m89vhf5g2vojp6tnqe58@group.calendar.google.com
  page: https://calendar.google.com/calendar/embed?showTitle=0&amp;showNav=0&amp;showDate=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0&amp;mode=AGENDA&amp;height=500&amp;wkst=2&amp;hl=cs&amp;bgcolor=%23FFFFFF&amp;src=nk73m1m89vhf5g2vojp6tnqe58%40group.calendar.google.com&ctz=Europe%2FPrague&amp;color=%232952A3

facebook:
  loadSDK: true
  profilePage: https://www.facebook.com/ceska.piratska.strana/
  profilePageName: Nějaký název FB profilu
  appId: 1526197851008996

twitter:
  loadSDK: true
  profile: PiratskaStrana

youtube:
  channel: UC_zxYLGrkmrYazYt0MzyVlA

instagram:
  profilePage: https://www.instagram.com/pirati.cz/

gplus:
  profilePage: https://plus.google.com/u/0/+piratskastrana

flicker:
  profilePage: https://www.flickr.com/photos/pirati/

forum:
  page: https://forum.pirati.cz/

github:
  url: https://github.com/texnokrates/jekyll-theme-piraatit/
  branch: master


assets:
  source_maps: true
  compression: true
  gzip: false
  plugins:
    css: { autoprefixer: {}}
    img:
      optim:
        jpegoptim:
          strip: all
          max_quality: 80
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
  sources:
    - node_modules
    - assets/css
    - assets/fonts
    - assets/video
    - assets/img
    - _sass
